name: Build project NodeJS
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          format: 'json'
          output: 'result.json'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'

      - name: Upload Trivy scan results
        uses: actions/upload-artifact@v4
        if: always() # Asegura que se suba incluso si Trivy encuentra vulnerabilidades y falla el paso anterior
        with:
          name: trivy-results
          path: 'result.json'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.9
        with:
          version: 11.9.0

      - name: Install Dependencies with pnpm
        run: pnpm ci

      - name: Build Project.
        run: pnpm run build
